### ISSUE TITLE
Missing icon?

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#43] opened 2019-08-19 10:34 UTC
I thought it should show something at the upper-left corner. In other weather conditions there's always something there.

![IMG_2276](https://user-images.githubusercontent.com/878399/63259028-a404f680-c27d-11e9-9732-817a52961d6d.JPG)

**Comment by aceisace** [comment] 2019-09-05 06:27
@surak 
Sorry, there is currently a bug with a few weather conditions. The problem is that the icon code for some weather conditions is not set correctly. This will also be fixed in the new release.

**Comment by surak** [comment] 2019-09-05 06:28
Thanks! :-)

**Comment by aceisace** [comment] 2019-10-09 08:07
@surak I've taken note of this bug in the Project-section of this repo. I'll try fixing this bug soon.

As the bug has been noted, I'll be closing this issue. If you feel a need to re-open this issue, please feel free to do so.

**Closed by aceisace** 2019-10-09 08:07 UTC
Labels: bug, on hold
